### ISSUE TITLE
Multiple duplicate entries for pages

### ISSUE THREAD

**Issue by micahsheets** [silverstripe-labs/silverstripe-googlesitemaps#107]
When I view the sitemap.xml for silverstripe sites in SS 3.3.1. I see multiple duplicate entries for the same urls. The url's have different priorities and change frequencies but are actually the same page. Is this intentional and if so what is the purpose?

**Comment by wilr** [comment]
You should not see duplicate entries for the same URL. You may want to check any registered dataobjects and custom routes define their own Link() methods.
