### ISSUE TITLE
issue with https protocol

### ISSUE THREAD

**Issue by Doniz** [silverstripe-labs/silverstripe-googlesitemaps#96]
i have in the server installed SSL certificate and domain is always using https. And when i trying to reflush the sitemap.xml i get an error with page not found. When i trying to run in the console:

`php framework/cli-script.php /sitemap.xml "flush=all"` i get the content of the xml. 

problem: not working with https.

**Comment by dhensby** [comment]
And it works with `http`?

**Comment by Doniz** [comment]
sorry for that, but looks like route is not mapped. With `http` not working too. I'm sure it's cache or server problem. 

Regards.
